name: alerter
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Restore previous state artifact (if available)
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: alerter.yml
          branch: main
          name: state
          workflow_conclusion: success
          if_no_artifact_found: warn
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: npm run build --if-present

      - name: Monitor packages and notify
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PACKAGES_TO_MONITOR: ${{ vars.PACKAGES_TO_MONITOR }}
          DISCORD_TITLE_TEMPLATE: ${{ vars.DISCORD_TITLE_TEMPLATE }}
          DISCORD_DESCRIPTION_TEMPLATE: ${{ vars.DISCORD_DESCRIPTION_TEMPLATE }}
          DISCORD_URL_TEMPLATE: ${{ vars.DISCORD_URL_TEMPLATE }}
        run: |
          node dist/index.js

      - name: Upload state artifact
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: .state
          if-no-files-found: ignore
          retention-days: 90
