name: alerter
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: npm run build --if-present

      - name: Monitor packages and notify
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PACKAGES_TO_MONITOR: ${{ vars.PACKAGES_TO_MONITOR }}
          DISCORD_TITLE_TEMPLATE: ${{ vars.DISCORD_TITLE_TEMPLATE }}
          DISCORD_DESCRIPTION_TEMPLATE: ${{ vars.DISCORD_DESCRIPTION_TEMPLATE }}
          DISCORD_URL_TEMPLATE: ${{ vars.DISCORD_URL_TEMPLATE }}
        run: |
          node dist/index.js

      - name: Commit state changes (if any)
        run: |
          if ! git diff --quiet -- .state 2>/dev/null; then
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add .state
            git commit -m "chore: update last seen versions [skip ci]"
            git push
          else
            echo "No state changes to commit."
          fi
